import Head from "next/head";
import styles from "../styles/Home.module.css";
import {  Card, Row, Col } from "react-bootstrap";
import Link from "next/link";
import Menu from "../components/navbar"
import firebase from "firebase/app";
import "firebase/auth";
import config from "../components/credentials";
import {
	FirebaseAuthProvider
  } from "@react-firebase/auth";

export default function Home() {
  return (
    <FirebaseAuthProvider firebase={firebase} {...config}>
    <div className={styles.container}>
      <Head>
        <title>Random Thoughts</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Menu />
      <main className={styles.main}>
          <div className="container">
            {productsBig.map((productList, index) => (
              <Row className="row pb-3 mb-3 fade-in" key={index}>
                <Col sm className={styles.card} style={{ maxWidth: "400px" }}>
                  <Link href={`/product/${productList[0].id}`}>
                    <a>
                      <Card.Img
                        variant="top"
                        className="img-fluid"
                        width="100%"
                        src={`/images/product/${productList[0]["imglink"]}`}
                        height="100%"
                        alt=""
                      />
                      <div
                        className="pb-2"
                        style={{ backgroundColor: "#131313" }}
                      >
                        <h6 className="" style={{ textAlign: "center" }}>
                          {productList[0].name}
                        </h6>
                        <h5
                          className="text-center"
                          style={{ color: "#05BECD" }}
                        >
                         Rs. {productList[1].price}
                        </h5>
                      </div>
                    </a>
                  </Link>
                </Col>

                <Col sm className={styles.card} style={{ maxWidth: "400px" }}>
                  <Link href={`/product/${productList[1].id}`}>
                    <a>
                      <Card.Img
                        className="img-fluid"
                        width="100%"
                        src={`/images/product/${productList[1]["imglink"]}`}
                        height="100%"
                        alt=""
                      />
                      <div
                        className="pb-2"
                        style={{ backgroundColor: "#131313" }}
                      >
                        <h6 className="" style={{ textAlign: "center" }}>
                          {productList[1].name}
                        </h6>
                        <h5
                          className="text-center"
                          style={{ color: "#05BECD" }}
                        >
                         Rs. {productList[1].price}
                        </h5>
                      </div>
                    </a>
                  </Link>
                </Col>
                <Col sm className={styles.card} style={{ maxWidth: "400px" }}>
                  <Link href={`/product/${productList[2].id}`}>
                    <a>
                      <Card.Img
                        className="img-fluid"
                        width="100%"
                        src={`/images/product/${productList[2]["imglink"]}`}
                        height="100%"
                        alt=""
                      />
                      <div
                        className="pb-2"
                        style={{ backgroundColor: "#131313" }}
                      >
                        <h6 className="" style={{ textAlign: "center" }}>
                          {productList[2].name}
                        </h6>
                        <h5
                          className="text-center"
                          style={{ color: "#05BECD" }}
                        >
                        Rs. {productList[1].price}
                        </h5>
                      </div>
                    </a>
                  </Link>
                </Col>
              </Row>
            ))}
        </div>
      </main>
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          
        </a>
      </footer>
    </div>
    </FirebaseAuthProvider>
  );
}
const products = [
  {
    name: "Dreamtime 1- Smart Jacket - RDKLU#26",
    price: "560",
    imglink:
      "RDKLU-3.1_540x.jpg",
  },
  {
    name: "Dreamtime 2- Smart Jacket - RDKLU#26",
    price: "560",
    imglink:
      "3d4e9213-a5fa-49fd-b4c5-a8230a41c5c01623477163682-HRX-by-Hrithik-Roshan-Men-Tshirts-9291623477163134-1.webp",
  },
  {
    name: "Dreamtime 3- Smart Jacket - RDKLU#26",
    price: "560",
    imglink:
      "08ea2923-1bfe-4f88-a13c-28be337b47681616398101252-HRX-by-Hrithik-Roshan-Women-Lavender-Self-Design-Round-Neck--1.webp",
  },
  {
    name: "Dreamtime - Smart Jacket - RDKLU#26",
    price: "560",
    imglink:
      "bbaf9359-ff91-4eaf-9df7-0de47d66f0731621236696234BlackPrintedShiftDressTshirtsRoadsterWomenTshirtsRoadsterWom1.webp",
  },
  {
    name: "Dreamtime - Smart Jacket - RDKLU#26",
    price: "560",
    imglink:
      "bbaf9359-ff91-4eaf-9df7-0de47d66f0731621236696234BlackPrintedShiftDressTshirtsRoadsterWomenTshirtsRoadsterWom1.webp",
  },
];
const productsBig = [
  [
    {
      id: 1,
      name: "Dreamtime 1- Smart Jacket - RDKLU#26",
      price: "560",
      imglink:
        "1_4164f62a-7e97-48bc-8b7c-c89a3a076ec0_900x.jpg",
    },
    {
      id: 2,
      name: "Dreamtime 2- Smart Jacket - RDKLU#26",
      price: "560",
      imglink:
        "1_z_3e75cd7d-50e4-434c-a27e-3f17a080292c_540x.jpg",
    },
    {
      id: 3,
      name: "Dreamtime 3- Smart Jacket - RDKLU#26",
      price: "560",
      imglink:
        "5_cb48f725-08c0-47a2-a0af-e769ac62363c_900x.jpg",
    },
  ],
  [
    {
      id: 4,
      name: "Dreamtime 4- Smart Jacket - RDKLU#26",
      price: "560",
      imglink:
        "5_cb48f725-08c0-47a2-a0af-e769ac62363c_900x.jpg",
    },
    {
      id: 5,
      name: "Dreamtime 5- Smart Jacket - RDKLU#26",
      price: "560",
      imglink:
        "115zz_900x.jpg",
    },
    {
      id: 6,
      name: "Dreamtime 6- Smart Jacket - RDKLU#26",
      price: "560",
      imglink:
      "115zz_900x.jpg",
    },
  ],
];
